service: serverless-pagespeed-monitoring

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 1536
  timeout: 180
  iamRoleStatements:
   -  Effect: "Allow"
      Action:
        - "cloudwatch:PutMetricData"
        - "cloudwatch:ListMetrics"
        - "cloudwatch:ListMetrics"
      Resource: "*"  

functions:
  pagespeed:
    handler: index.handler
    events:
      - schedule:
          rate: ${file(./config.yml):rate}
          enabled: true
    environment:
      DEBUG: 0
      url: ${file(./config.yml):url}
      metrics: ${file(./config.yml):metrics}

package:
  artifact: ./package.zip
  
plugins:
  - serverless-hooks-plugin
  - serverless-sam

custom:
  hooks:
    package:initialize:
      - npm run package